// app/manifest.js
// File-convention web manifest -> served at /manifest.webmanifest, auto-linked in <head>.
// PWA icons point at the STATIC public/ PNGs (stable absolute URLs) generated by
// scripts/gen-icons.mjs -- the same 'CNP' burgundy mark. theme_color = network burgundy,
// background_color = the dark site bg (globals.css --bg-page).

export default function manifest() {
  return {
    name: 'Cybernetic Punks',
    short_name: 'Cybernetic Punks',
    description: 'The competitive-shooter intelligence network.',
    start_url: '/',
    display: 'standalone',
    theme_color: '#b32d40',
    background_color: '#121418',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
